default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: SQL6521
  timeout: 5000

development:
  <<: *default
  database: dab-blog_development

test: &test
  <<: *default
  database: dab-blog_test

production:
  <<: *default
  database: dab-blog_production
  username: dab-blog
  password: <%= ENV['DAB-BLOG_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
